### ISSUE TITLE
Rename `transform:` API due to App Store Rejections

### ISSUE THREAD

**Issue by ryanwilson** [google/GoogleDataTransport#10]
Originally reported in https://github.com/firebase/firebase-ios-sdk/issues/7177

The existing `transform:` public API can lead to false-positives regarding private API usage in the App Store. We should rename it to avoid this, likely adding a prefix, renaming to `transformGDTEvent:`, or something similar.

https://github.com/google/GoogleDataTransport/blob/c654af7fa7a4b50df690ea9adc53f68e893c87ff/GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCOREventTransformer.h#L34

This is a breaking change, so all dependencies need to be updated as well.

**Comment by paulb777** [comment]
Fixed by #18
