### ISSUE TITLE
[FR]: Support for Apple Privacy Info Manifest-Files

### ISSUE THREAD

**Issue by faken** [google/GoogleDataTransport#114]
Apple will enforce the requirement for a privacy info manifest file for all third party libraries this year.
More information can be looked up here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
The library needs to be updated to include a privacy info manifest-file

**Comment by ncooke3** [comment]
Thanks @faken, this is being actively worked on in combination with https://github.com/firebase/firebase-ios-sdk/issues/11490

**Comment by viharshitha** [comment]
Which GoogleDataTransport version has the privacy manifest?

**Comment by paulb777** [comment]
Introduced in 9.4.0. See https://github.com/google/GoogleDataTransport/releases

**Comment by viharshitha** [comment]
Thank you for your response. After creating a privacy manifest report and archiving my app, I have the attached the expxorted report, Is something wrong? What do I want to do for it? Please help on it. 

<img width="541" alt="Image" src="https://github.com/user-attachments/assets/fc5c5483-2ea6-4273-b74d-179ab93153f3" />

[myfile.pdf](https://github.com/user-attachments/files/18870424/myfile.pdf)

**Comment by ncooke3** [comment]
@viharshitha, that looks like the privacy manifest for GDT is correctly being found by Xcode. This looks correct to me.

**Comment by viharshitha** [comment]
we are using @capacitor-mlkit/barcode-scanning in our ionic App, which is interlink dependent with GoogleToolboxForMac. Recently we got an email from apple store regarding Missing privacy manifest. We try to upgrade @capacitor-mlkit/barcode-scanning which is internally updated GoogleToolboxForMac version to 4.2.0. but once I ran xcode for privacy report, it is not showing up in xcode. Any idea on it(if privacy manifest is added that should be shown up xcode generated report, right?) please help me n correct me


podfile.lock

 - MLKitBarcodeScanning (6.0.0):
    - MLKitCommon (~> 12.0)
    - MLKitVision (~> 8.0)
  - MLKitCommon (12.0.0):
    - GoogleDataTransport (~> 10.0)
    - GoogleToolboxForMac/Logger (< 5.0, >= 4.2.1)
    - "GoogleToolboxForMac/NSData+zlib (< 5.0, >= 4.2.1)"
    - GoogleUtilities/Logger (~> 8.0)
    - GoogleUtilities/UserDefaults (~> 8.0)
    - GTMSessionFetcher/Core (< 4.0, >= 3.3.2)
  - MLKitVision (8.0.0):
    - GoogleToolboxForMac/Logger (< 5.0, >= 4.2.1)
    - "GoogleToolboxForMac/NSData+zlib (< 5.0, >= 4.2.1)"
    - GTMSessionFetcher/Core (< 4.0, >= 3.3.2)
    - MLImage (= 1.0.0-beta6)
    - MLKitCommon (~> 12.0)


Apple Email:
ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac”, which includes GoogleToolboxForMac, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting February 12, 2025, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests,
