### ISSUE TITLE
The dependency version on cocoapods is incorrect

### ISSUE THREAD

**Issue by percival888** [google/GoogleDataTransport#119]
I found that 9.4.0 version on Cocoapods，the version range marked with nanoPB is < 2.30910.0, which is inconsistent with the actual code.

Can you re release a correct version

https://github.com/CocoaPods/Specs/blob/master/Specs/0/6/a/GoogleDataTransport/9.4.0/GoogleDataTransport.podspec.json

**Comment by percival888** [comment]
![截屏2024-03-06 19 01 33](https://github.com/google/GoogleDataTransport/assets/19942237/043b35fc-c9dc-4c32-9c70-71a92f1eb57c)

**Comment by ncooke3** [comment]
@percival888,  I just re-released the pod in a 9.4.1 release. Please pod update to get this fix. Sorry for the trouble, but thanks for reporting!
