### ISSUE TITLE
Getting `Null pointer passed as argument 1, which is declared to never be null`

### ISSUE THREAD

**Issue by michalsrutek** [google/GoogleDataTransport#124]
## ℹ️ 

Getting `Null pointer passed as argument 1, which is declared to never be null` message from https://github.com/google/GoogleDataTransport/blob/6e27aa51abc4847ba748f3ea11bb0a1f3d09f5d3/GoogleDataTransport/GDTCORLibrary/GDTCORLogSourceMetrics.m#L55

## 🖼️ 
![Screenshot 2024-05-12 at 8 22 24](https://github.com/google/GoogleDataTransport/assets/35694712/8ee88260-4657-4d54-a006-8439a0572833)

**Comment by ncooke3** [comment]
Thanks for the report, @michalsrutek. This will be released in the next update of GoogleDataTransport. In the meantime, this should not cause crashes as the current undocumented behavior of that API is to return an empty dictionary when `nil` is passed.
