### ISSUE TITLE
Missing whitespace in podspec's `preprocessor_definitions` is leading to quietly broken config

### ISSUE THREAD

**Issue by Westacular** [google/GoogleDataTransport#138]
The podspec has

```
  preprocessor_definitions =
      'PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1'\
      'GDTCOR_VERSION=' + s.version.to_s
```

with a line continuation _but no whitespace_ between `PB_ENABLE_MALLOC=1` and `GDTCOR_VERSION=`, so the resulting xcconfig contains `... PB_ENABLE_MALLOC=1GDTCOR_VERSION=9.4.1 ...` which is (quietly) invalid.

But the fact that it's been this way for two years without anyone noticing makes me wonder if either of the `PB_ENABLE_MALLOC=1` or `GDTCOR_VERSION` definitions actually matter?

**Comment by ncooke3** [comment]
Nice find, @Westacular! It doesn't look like they are critical to the SDK's function, but worth fixing for completeness.

**Comment by paulb777** [comment]
I'm almost certain PB_ENABLE_MALLOC matters, but probably any truthy value for it is fine.

The GDTCOR_VERSION seems to be used for logging that must not be monitored?
