### ISSUE TITLE
unknown library issue iosawnfcmdist library under googledatatransport

### ISSUE THREAD

**Issue by Gmakode** [google/GoogleDataTransport#145]
IN Blackduck scan we observed that googledatatranport is dynamically linking iosawnfcmdist library with its latest version 0.9.3 which is unknow license. Any way to restrict the version of the library iosawnfcmdist or ignore the linkage

**Comment by paulb777** [comment]
I don't see a reference to iosawnfcmdist from GoogleDataTransport. Please provide more details.
