### ISSUE TITLE
Compatibility Issue: GoogleDataTransport (9.4.1) and Firebase Analytics (nanopb version conflict)

### ISSUE THREAD

**Issue by AndreyDAraya** [google/GoogleDataTransport#149]
Description: There is a compatibility issue between GoogleDataTransport (9.4.1) and Firebase Analytics regarding the version of nanopb they depend on.

GoogleDataTransport (9.4.1) has the following dependencies:

```
GoogleUtilities/Environment (~> 7.7)
nanopb (< 2.30911.0, >= 2.30908.0)
Firebase Analytics requires nanopb (~> 3.30910.0).
```

Because of this, it is impossible to resolve dependencies when using both GoogleDataTransport (9.4.1) and Firebase Analytics in the same project. GoogleDataTransport does not support the required version of nanopb needed by Firebase Analytics.

Steps to Reproduce:

Create a project with Firebase Analytics and GoogleDataTransport.
Attempt to install dependencies using CocoaPods.
Observe the dependency conflict error regarding the incompatible nanopb versions.
Expected Behavior: GoogleDataTransport should be updated to support nanopb (~> 3.30910.0) to ensure compatibility with Firebase Analytics and other Firebase libraries.

Environment:

GoogleDataTransport version: 9.4.1
Firebase Analytics version: Latest
CocoaPods version: 1.15.2
Xcode version: 15.4
Operating System: Sonoma
Additional Context: Please update GoogleDataTransport to be compatible with the latest version of nanopb or provide guidance on how to resolve this dependency conflict. 

Specify to Flutter applications.
ML-Kit-Google and Firebase

**Comment by paulb777** [comment]
This issue is addressed with GoogleDataTransport 10.x.

Until MLKit updates its dependency, it may be necessary to stay with FirebaseAnalytics 10.x.
