### ISSUE TITLE
Call to undeclared function 'pb_release'; ISO C99 and later do not support implicit function declarations

### ISSUE THREAD

**Issue by DIGITALSQUAD** [google/GoogleDataTransport#153]
GDTCORMetrics+GDTCCTSupport.m shows an error in Xcode version 16.0.

Line: 82 
````
pb_release(gdt_client_metrics_ClientMetrics_fields, &clientMetricsProto);
````
**Call to undeclared function 'pb_release'; ISO C99 and later do not support implicit function declarations**

![Image](https://github.com/user-attachments/assets/f33e6b91-3b12-4076-a223-052022e87191)

- GoogleDataTransport 10.1.0
- nanopb 3.30910.0

**Comment by ncooke3** [comment]
Hi @DIGITALSQUAD, how are you integrating this into your project? CocoaPods, SwiftPM, Zip, Carthage?

**Comment by DIGITALSQUAD** [comment]
Hi @ncooke3 I use CocoaPods.

**Comment by ncooke3** [comment]
Do any of the following posts help? https://github.com/firebase/firebase-ios-sdk/issues/6741 or https://stackoverflow.com/questions/70881373/firebase-does-not-build-for-ios-in-flutter-implicit-declaration-of-function-p ?

The GDT podspec enables the `PB_ENABLE_MALLOC` preprocessor flag, which will in turn compile the`pb_release` API.

**Comment by DIGITALSQUAD** [comment]
The second one solved the issue!  
Thank you for your support.

I added **'$(inherited)'** in  GCC_PREPROCESSOR_DEFINITIONS.

Podfile
````
target 'MyApp' do
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '$(inherited)' # Added this line
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'GLES_SILENCE_DEPRECATION=1'
      end
    end
  end
end
````
