### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by anabeatrizzz** [google/GoogleDataTransport#24]
I'm developing a React Native app and when I run `react-native run-ios` I receive this error related with `GoogleDataTransport`:

_The following build commands failed:
	CompileC /Users/fair/Library/Developer/Xcode/DerivedData/FairMobile-bqgeuszvlfcgenemmqawwkroifuq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/GoogleDataTransport.build/Objects-normal/x86_64/GDTCCTUploadOperation.o /Users/fair/Documents/fair-mobile-react-native/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)_

How can I proceed?

**Comment by paulb777** [comment]
@anabeatrizzz Sorry about the trouble. This is most likely a react-native configuration issue and it would be better to ask for help on a react-native channel.
