### ISSUE TITLE
Memory leak or cycle reference question

### ISSUE THREAD

**Issue by LittleXu** [google/GoogleDataTransport#33]
![image](https://user-images.githubusercontent.com/15767257/125723949-b9a2a791-d2cc-4fff-9eb3-0ec5185468ed.png)

Will this place cause a cycle reference?

**Comment by maksymmalyhin** [comment]
@LittleXu It seems like an old version of GoogleDataTransport SDK is used in your app. The memory leak was fixed in the version [8.3.1](https://github.com/google/GoogleDataTransport/blob/main/CHANGELOG.md#v831).

Could you please try to update the SDK and let us know if you still have issues.

**Comment by LittleXu** [comment]
I have updated it to the latest version and it has no memory leak problem，thanks a lot
