### ISSUE TITLE
Can the client use only the most secure protocols?

### ISSUE THREAD

**Issue by limyeewee** [google/GoogleDataTransport#47]
Can the client use only the most secure protocols?

https://github.com/google/GoogleDataTransport/blob/25449cd3dc7f4583407c81748c880fbf433c95dc/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m#L106

**Comment by ncooke3** [comment]
Hi @limyeewee, 

I don't quite understand your question, could you please explain your question further? Thanks!

**Comment by ncooke3** [comment]
Closing due to staleness
