### ISSUE TITLE
Undefined symbol: _GDTCCTConstructiOSClientInfo

### ISSUE THREAD

**Issue by thinkbizd29** [google/GoogleDataTransport#94]
![Screenshot 2023-04-20 at 10 34 32 AM](https://user-images.githubusercontent.com/131333388/233263620-00a4182d-667f-471c-a74b-1f0c7aec9349.png)

This issue occured after update xcode 14.2 to 14.3.

**Comment by ncooke3** [comment]
@thinkbizd29, what package manager are you using Firebase with?

**Comment by TheMartas29** [comment]
Same problem here. Did anyone manage to fix this?

**Comment by ncooke3** [comment]
Hi @TheMartas29 , are you able to provide a reproducible example?

**Comment by TheMartas29** [comment]
I guess I fixed it. 
I added compiler flag "-fno-objc-msgsend-selector-stubs" for **GDTCCNanopbHelepers.m** in Build Phases - Compile Sources (screenshot 1). That solved it for builds on emulator but not for Archive / TestFlight builds. So I changed **projectName-frameworks.sh** file on line 44. I added "-f" parameter (screenshot 2). I also tried changing minimum deployment iOS version. That didn't work for this Pod but it solved issues with other Pods.

I hope it helps somebody :)

![Snímek obrazovky 2023-05-04 v 18 57 03](https://user-images.githubusercontent.com/73795239/236274134-2c8fbb89-664f-4c0a-9292-0a7219528e8f.png)

![Snímek obrazovky 2023-05-04 v 19 02 33](https://user-images.githubusercontent.com/73795239/236274975-bd6e7648-8ae9-412e-b790-5f7209b47efa.png)

**Comment by TheMartas29** [comment]
I was trying to find why we are even using this library but I can't find it. Our project is cordova based and we are using lot of third party plugins including some plugins that use Google libraries / Pods, such as Firebase/Messaging that is being installed by this cordova plugin: https://github.com/havesource/cordova-plugin-push. But I can't find why the GoogleDataTransport is being installed.

**Comment by thinkbizd29** [comment]
Hello, 
I resolved this issue by upgrading specific this google transport pod,
refer this link https://stackoverflow.com/questions/76021583/latest-version-cordova-xcode-linker-command-failed-with-exit-code-1/76363040#76363040
